enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@devtools-ds/object-inspector@1.2.0":
    peerDependencies:
      react-dom: ">=17.0.2"
  "@devtools-ds/themes@1.2.0":
    peerDependencies:
      react-dom: ">=17.0.2"
  "@devtools-ds/tree@1.2.0":
    peerDependencies:
      react-dom: ">=17.0.2"
  "@storybook/addon-docs@6.5.10":
    peerDependencies:
      "@babel/core": ^7.18.10
      webpack: ^5.74.0
  "@storybook/docs-tools@6.5.10":
    peerDependencies:
      "@babel/core": ^7.18.10
      react: ">=17.0.2"
      react-dom: ">=17.0.2"
  "@storybook/instrumenter@6.5.10":
    peerDependencies:
      react: ">=17.0.2"
      react-dom: ">=17.0.2"
  "@storybook/mdx1-csf@0.0.1":
    peerDependencies:
      "@babel/core": ^7.18.10
  "@storybook/telemetry@6.5.10":
    peerDependencies:
      react: ">=17.0.2"
      react-dom: ">=17.0.2"
  "@storybook/testing-library@0.0.13":
    peerDependencies:
      react: ">=17.0.2"
      react-dom: ">=17.0.2"

yarnPath: .yarn/releases/yarn-3.2.2.cjs
